### ISSUE TITLE
if i'm hope show Badge text on Button's center?

### ISSUE THREAD

**Issue by arden** [mustafaibrahim989/MIBadgeButton-Swift#10]
if i'm hope show Badge text on Button's center?
What should I do?

**Comment by mustafaibrahim989** [comment]
Sure, this will be implemented soon in the next release. For now just use UIEdgeInsetsMake as follows  `UIEdgeInsetsMake(0.0, 0.0, buttonSize.height+spacing, -buttonSize.width)`

Thanks

**Comment by tomneo2004** [comment]
mustafaibrahim989
I have made a pull request that can put badge on 4 different position on button include center

**Comment by mustafaibrahim989** [comment]
Fixed. Please see #17
