### ISSUE TITLE
Xcode 8

### ISSUE THREAD

**Issue by cosmo1234** [mustafaibrahim989/MIBadgeButton-Swift#12]
Am getting a lot of errors with xcode 8 beta 6

**Comment by elprl** [comment]
Advise a swift2.3 and swift3 branch for cocoapod users. e.g.
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'swift3'

**Comment by elprl** [comment]
Why was this closed?

**Comment by mustafaibrahim989** [comment]
@cosmo1234 It's fixed now. 👍

**Comment by mustafaibrahim989** [comment]
@elprl Done. Thanks for your help 👍
