### ISSUE TITLE
UIBarButtonItem

### ISSUE THREAD

**Issue by jedgrant** [mustafaibrahim989/MIBadgeButton-Swift#2]
It would be fantastic to have an easy way to use this on a UIBarButtonItem. Any chance you will extend it to cover this? I want to use this for a notification count indicator badge.

**Comment by mustafaibrahim989** [comment]
You can assign MIBadgeButton to UIBarButtonItem customView by  
```
var rightItem:UIBarButtonItem = UIBarButtonItem()
rightItem.customView = MIBadgeButtonObject
self.navigationItem.rightBarButtonItem = rightItem
```
