### ISSUE TITLE
Adding badge to system UIBarButtonItem

### ISSUE THREAD

**Issue by stephen-talari** [mustafaibrahim989/MIBadgeButton-Swift#20]
How to add badge on top of system BarButtonItem of specific style (ex. bookmarked) 

i am able to set my own image by `button.setImage(UIImage(named: "filter_icon"), forState: .Normal)`. But how can we use system `UIBarButtonSystemItem`  images?

Any help!

**Comment by mustafaibrahim989** [comment]
Duplicate issue. Please see [https://github.com/mustafaibrahim989/MIBadgeButton-Swift/issues/5](url)
