### ISSUE TITLE
iOS 9 Xcode 7.0GM issue

### ISSUE THREAD

**Issue by coolagrwal** [mustafaibrahim989/MIBadgeButton-Swift#3]
Hi Mustafa, 

I am facing issue on this line, in code that you have shared:

labelString.drawInRect(textFrame, withAttributes: attributes as [NSObject: AnyObject])  // issue is here 

Message: [NSObject: AnyObject] cannot be converted to expected type [String : AnyObject]?

Pankaj Bansal

**Comment by mustafaibrahim989** [comment]
Thanks for the opened issue. It's support Xcode 7 and swift 2.0.
