### ISSUE TITLE
Getting warning message when installing from CocoaPods

### ISSUE THREAD

**Issue by LuaiKalkatawi** [mustafaibrahim989/MIBadgeButton-Swift#6]
Thank you for this great work. I would like to tell you I'm getting this warning message from the terminal when I install MIBadgeButton via  CocoaPods. @mustafaibrahim989 

`[!] Unable to read the license file /Users/username/appname.iOS/Pods/MIBadgeButton-Swift/mit-license.txt for the spec MIBadgeButton-Swift (0.1)` `

**Comment by mustafaibrahim989** [comment]
Fixed :+1: in version 0.3
