### ISSUE TITLE
"Use of undeclared type MiBadgeButton"

### ISSUE THREAD

**Issue by uknowmeright** [mustafaibrahim989/MIBadgeButton-Swift#7]
throwing my this error when I try to add a button to storyboard and give it the MiBadgeButton class and add an IBOutlet to it in code:

"Use of undeclared type MiBadgeButton"

i have tried:

`import MIBadgeButton_Swift`

but it does not seem to help.

Any Ideas?

**Comment by Treverr** [comment]
Same issue here.

**Comment by Treverr** [comment]
@uknowmeright I copied the MIBadgeButton.swift file into my project for now, and it works.

**Comment by mustafaibrahim989** [comment]
Guys, sorry for being late, I will work on it today and let you know. Thanks for your note :+1: .

**Comment by mustafaibrahim989** [comment]
Fixed :+1:

**Comment by markvillaflor** [comment]
I am still having this problem.

**Comment by markvillaflor** [comment]
@mustafaibrahim989 pls help.

**Comment by mustafaibrahim989** [comment]
@markvillaflor  Did you import MIBadgeButton-Swift?

**Comment by bewithdhanu** [comment]
I have tried both
`import MIBadgeButton-Swift`
`import MIBadgeButton_Swift`
none of those are worked for me, can help anyone plz?
